SELECT * FROM PRODUCTS
SELECT * FROM PRODUCTS WHERE UnitsInStock >= 40
SELECT * FROM CUSTOMERS WHERE CITY = 'LONDON' 
SELECT * FROM ORDERS ORDER BY FREIGHT DESC
SELECT * FROM ORDERS WHERE FREIGHT BETWEEN 90 AND 200
SELECT * FROM PRODUCTS WHERE CATEGORYID = 1
SELECT * FROM [Order Details] WHERE DISCOUNT != 0
SELECT * FROM ORDERS WHERE CUSTOMERID = 'BOTTM' AND FREIGHT > 50
